# Generated by Django 5.0.4 on 2024-09-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_rename_tel_userprofile_phone_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='tel',
        ),
    ]
